"""
CEO Briefing Generator - Gold Tier
Generates weekly "Monday Morning CEO Briefing" reports

Per hackathon document:
"Weekly Business and Accounting Audit with CEO Briefing generation"

Analyzes:
- Completed tasks from /Done
- Revenue indicators
- Bottlenecks (tasks that took too long)
- Proactive suggestions from Business_Goals.md
"""
from pathlib import Path
from datetime import datetime, timedelta
from qwen_agent import ask_qwen
import re

VAULT = Path("AI_Employee_Vault")
DONE = VAULT / "Done"
LOGS = VAULT / "Logs"
BRIEFINGS = VAULT / "Briefings"
BUSINESS_GOALS = VAULT / "Business_Goals.md"


def safe_read(file_path: Path) -> str:
    try:
        return file_path.read_text(encoding="utf-8")
    except UnicodeDecodeError:
        return file_path.read_text(encoding="latin-1")


def safe_write(file_path: Path, content: str):
    file_path.write_text(content, encoding="utf-8")


def get_completed_tasks(days: int = 7) -> list:
    """Get tasks completed in the last N days"""
    cutoff = datetime.now() - timedelta(days=days)
    tasks = []

    for task_file in DONE.glob("*.md"):
        try:
            # Extract timestamp from filename or content
            content = safe_read(task_file)
            # Look for timestamps in content
            timestamps = re.findall(r'\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}', content)
            if timestamps:
                task_time = datetime.fromisoformat(timestamps[0])
                if task_time >= cutoff:
                    tasks.append({
                        "file": task_file.name,
                        "content": content[:500],
                        "timestamp": task_time.isoformat()
                    })
        except Exception:
            continue

    return tasks


def get_logs(days: int = 7) -> list:
    """Get log entries from the last N days"""
    entries = []
    cutoff = datetime.now() - timedelta(days=days)

    for i in range(days):
        date = (datetime.now() - timedelta(days=i)).strftime("%Y-%m-%d")
        log_file = LOGS / f"{date}.md"

        if log_file.exists():
            try:
                content = safe_read(log_file)
                # Extract error entries
                errors = re.findall(r'## \[.*?\] (error|failed).*?\n(.*?)(?=\n##|\n\n\n)', content, re.DOTALL)
                for error_type, details in errors:
                    entries.append({
                        "type": error_type,
                        "details": details.strip()[:200]
                    })
            except Exception:
                continue

    return entries


def analyze_performance(tasks: list, logs: list) -> str:
    """Use AI to analyze performance data"""
    task_summary = f"Completed {len(tasks)} tasks in the past week"

    error_summary = ""
    if logs:
        error_summary = f"\n\nErrors/Issues:\n"
        for entry in logs[:5]:
            error_summary += f"- {entry['type']}: {entry['details']}\n"

    prompt = f"""
Analyze the business performance for this week:

Tasks: {task_summary}
{error_summary}

Based on the Business Goals and completed tasks, generate a CEO Briefing with:

1. Executive Summary (2-3 sentences)
2. Completed Tasks summary
3. Bottlenecks identified (tasks that failed or had issues)
4. Revenue/Trend analysis if applicable
5. Proactive suggestions for improvement
6. Upcoming deadlines to watch

Format as clean markdown.
"""

    try:
        return ask_qwen(prompt, "CEO Briefing Analysis")
    except Exception as e:
        return f"# CEO Briefing\n\nAnalysis failed: {e}\n\n## Completed Tasks\n{len(tasks)} tasks completed this week"


def generate_briefing(days: int = 7) -> Path:
    """Generate a complete CEO Briefing"""
    print(f"[Briefing] Generating CEO Briefing for past {days} days...")

    # Gather data
    tasks = get_completed_tasks(days)
    logs = get_logs(days)

    # Load business goals
    goals = ""
    if BUSINESS_GOALS.exists():
        goals = safe_read(BUSINESS_GOALS)

    # Analyze performance
    analysis = analyze_performance(tasks, logs)

    # Build briefing
    briefing_date = datetime.now().strftime("%Y-%m-%d")
    period_start = (datetime.now() - timedelta(days=days)).strftime("%Y-%m-%d")

    briefing = f"""---
generated: {datetime.now().isoformat()}
period: {period_start} to {briefing_date}
type: ceo_briefing
---

# Monday Morning CEO Briefing

**Period:** {period_start} to {briefing_date}
**Generated:** {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}

---

{analysis}

---

## Business Goals Reference

{goals}

---

*Generated by AI Employee v0.3 - Gold Tier*
"""

    # Save briefing
    BRIEFINGS.mkdir(exist_ok=True)
    briefing_file = BRIEFINGS / f"{briefing_date}_CEO_Briefing.md"
    safe_write(briefing_file, briefing)

    print(f"[Briefing] Briefing saved: {briefing_file.name}")

    # Log generation
    log_file = LOGS / f"{briefing_date}.md"
    if log_file.exists():
        log_content = safe_read(log_file)
    else:
        log_content = f"# Activity Log - {briefing_date}\n\n"

    log_content += f"""
## [{datetime.now().isoformat()}] CEO Briefing Generated
- **Period:** {period_start} to {briefing_date}
- **Tasks Analyzed:** {len(tasks)}
- **Briefing:** {briefing_file.name}

"""
    safe_write(log_file, log_content)

    return briefing_file


if __name__ == "__main__":
    result = generate_briefing()
    print(f"\nBriefing generated: {result}")
