"""
File System Watcher - Bronze Level Implementation
Monitors drop_folder and creates action files in /Inbox (NOT directly in Needs_Action)

Per document spec:
- Watchers feed /Inbox
- Orchestrator moves /Inbox → /Needs_Action
- AI processes /Needs_Action
"""
from watchdog.observers import Observer
from watchdog.events import FileSystemEventHandler
from pathlib import Path
import shutil
import time
from datetime import datetime

VAULT = Path("AI_Employee_Vault")
DROP_FOLDER = Path("drop_folder")
INBOX = VAULT / "Inbox"


class DropFolderHandler(FileSystemEventHandler):
    """
    Handles file creation events in the drop folder.
    Creates action files in /Inbox per document architecture.
    """

    def __init__(self, vault_path: Path):
        self.vault_path = vault_path
        self.inbox = vault_path / "Inbox"

    def on_created(self, event):
        """Called when a file is created in the drop folder"""
        if event.is_directory:
            return

        src = Path(event.src_path)

        # Skip hidden files and temporary files
        if src.name.startswith('.') or src.suffix == '.tmp':
            return

        # Create unique filename with timestamp
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        dest_name = f"FILE_{timestamp}_{src.name}"
        dest = self.inbox / dest_name

        try:
            # Copy file to Inbox (NOT Needs_Action)
            shutil.copy2(src, dest)

            # Create metadata file with proper frontmatter
            self.create_metadata(src, dest)

            print(f"[Watcher] New file detected: {src.name} -> {dest_name}")

        except Exception as e:
            print(f"[Watcher] Error processing file: {e}")

    def create_metadata(self, source: Path, dest: Path):
        """Create a .md metadata file for the dropped file"""
        meta_path = dest.with_suffix('.md')

        content = f"""---
type: file_drop
original_name: {source.name}
size: {source.stat().st_size}
created: {datetime.now().isoformat()}
status: new
source: drop_folder
---

# File Drop for Processing

**Original File:** `{source.name}`
**Size:** {source.stat().st_size} bytes
**Received:** {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}

## Content
Awaiting AI analysis and action plan.

## Suggested Actions
- [ ] Analyze file content
- [ ] Determine required actions
- [ ] Create plan in /Plans
- [ ] Execute or request approval

---
*Generated by File System Watcher v0.1*
"""
        meta_path.write_text(content, encoding="utf-8")
        print(f"[Watcher] Metadata created: {meta_path.name}")


def run_watcher():
    """Start the file system watcher"""
    # Ensure directories exist
    VAULT.mkdir(exist_ok=True)
    INBOX.mkdir(exist_ok=True)
    DROP_FOLDER.mkdir(exist_ok=True)

    # Start observer
    event_handler = DropFolderHandler(VAULT)
    observer = Observer()
    observer.schedule(event_handler, str(DROP_FOLDER), recursive=False)
    observer.start()

    print("[Watcher] File System Watcher started")
    print(f"[Watcher] Monitoring: {DROP_FOLDER.absolute()}")
    print(f"[Watcher] Output: {INBOX}")
    print("[Watcher] Press Ctrl+C to stop")

    try:
        while True:
            time.sleep(5)
    except KeyboardInterrupt:
        observer.stop()
        print("[Watcher] Watcher stopped")

    observer.join()


if __name__ == "__main__":
    run_watcher()
