"""
LinkedIn MCP Server - Silver Level Implementation
Allows AI Employee to post updates to LinkedIn automatically

Per hackathon document Silver Tier:
"Automatically Post on LinkedIn about business to generate sales"

IMPORTANT: This is a DRAFT-ONLY implementation per document security rules.
All posts require human approval before actual posting.
"""
from flask import Flask, request, jsonify
from pathlib import Path
from datetime import datetime
import requests
import os
from dotenv import load_dotenv

load_dotenv()

app = Flask(__name__)

VAULT = Path("AI_Employee_Vault")

# LinkedIn API Configuration
# Get these from LinkedIn Developer Portal: https://www.linkedin.com/developers/
LINKEDIN_API_BASE = "https://api.linkedin.com/v2"


# ==============================
# HEALTH CHECK
# ==============================
@app.route("/", methods=["GET"])
def home():
    return jsonify({
        "status": "LinkedIn MCP Server Running",
        "version": "0.1 - Silver Level",
        "endpoints": [
            "/create-post (POST)",
            "/schedule-post (POST)",
            "/status (GET)"
        ]
    })


# ==============================
# CREATE LINKEDIN POST (DRAFT)
# ==============================
@app.route("/create-post", methods=["POST"])
def create_post():
    """
    Create a LinkedIn post draft.
    Writes to /Inbox per hackathon document architecture.
    
    Correct flow:
    MCP → /Inbox → Orchestrator → /Needs_Action → AI → Plans → /Pending_Approval → Approved → Done
    
    Expected JSON:
    {
        "text": "Post content",
        "title": "Optional title",
        "visibility": "PUBLIC" | "CONNECTIONS"
    }
    """
    data = request.json

    text = data.get("text", "")
    title = data.get("title", "Business Update")
    visibility = data.get("visibility", "PUBLIC")

    if not text:
        return jsonify({
            "status": "error",
            "message": "Post text is required"
        }), 400

    # FIX: Write to /Inbox (NOT /Pending_Approval)
    # Orchestrator will move to /Needs_Action, then AI processes
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    inbox_file = VAULT / "Inbox" / f"LINKEDIN_POST_{timestamp}.md"

    content = f"""---
type: linkedin_post
source: mcp
title: {title}
visibility: {visibility}
status: new
created: {timestamp}
---

# LinkedIn Post Request

**Title:** {title}
**Visibility:** {visibility}
**Created:** {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}

## Post Content

{text}

---

## Note

This post will be processed by the AI Employee:
1. Orchestrator moves it to /Needs_Action
2. AI creates action plan
3. Approval requested if needed
4. Human approves in /Pending_Approval
5. Post published to LinkedIn

*Generated by LinkedIn MCP Server v0.1*
"""

    inbox_file.write_text(content, encoding="utf-8")

    return jsonify({
        "status": "success",
        "message": "LinkedIn post draft created in Inbox",
        "inbox_file": inbox_file.name,
        "note": "Post will be processed through normal workflow: Inbox → Needs_Action → Plans → Approval → Done"
    })


# ==============================
# EXECUTE LINKEDIN POST
# ==============================
@app.route("/execute-post", methods=["POST"])
def execute_post():
    """
    Execute an approved LinkedIn post.
    Called by orchestrator when approval file is moved to /Approved.
    """
    data = request.json
    
    post_content = data.get("text", "")
    access_token = os.getenv("LINKEDIN_ACCESS_TOKEN")
    
    if not access_token:
        return jsonify({
            "status": "error",
            "message": "LinkedIn access token not configured. Set LINKEDIN_ACCESS_TOKEN in .env"
        }), 500
    
    try:
        # Get authenticated user's URN
        headers = {
            "Authorization": f"Bearer {access_token}",
            "Content-Type": "application/json",
            "X-Restli-Protocol-Version": "2.0.0"
        }
        
        # Get person URN
        person_response = requests.get(
            f"{LINKEDIN_API_BASE}/me",
            headers=headers
        )
        
        if person_response.status_code != 200:
            return jsonify({
                "status": "error",
                "message": f"Failed to get user info: {person_response.text}"
            }), 500
        
        person_urn = person_response.json().get("id")
        author_urn = f"urn:li:person:{person_urn}"
        
        # Create post
        post_data = {
            "author": author_urn,
            "lifecycleState": "PUBLISHED",
            "specificContent": {
                "com.linkedin.ugc.ShareContent": {
                    "shareCommentary": {
                        "text": post_content
                    },
                    "shareMediaCategory": "NONE"
                }
            },
            "visibility": {
                "com.linkedin.ugc.MemberNetworkVisibility": "PUBLIC"
            }
        }
        
        post_response = requests.post(
            f"{LINKEDIN_API_BASE}/ugcPosts",
            headers=headers,
            json=post_data
        )
        
        if post_response.status_code == 201:
            post_id = post_response.json().get("id")
            
            # Log successful post
            log_linkedin_post(post_content, post_id, "success")
            
            return jsonify({
                "status": "success",
                "message": "Post published to LinkedIn",
                "post_id": post_id
            })
        else:
            return jsonify({
                "status": "error",
                "message": f"Failed to post: {post_response.text}"
            }), 500
            
    except Exception as e:
        return jsonify({
            "status": "error",
            "message": str(e)
        }), 500


# ==============================
# SCHEDULE LINKEDIN POST
# ==============================
@app.route("/schedule-post", methods=["POST"])
def schedule_post():
    """
    Schedule a LinkedIn post for later.
    Writes to /Inbox per hackathon document architecture.
    
    Expected JSON:
    {
        "text": "Post content",
        "scheduled_time": "2026-01-15T09:00:00"
    }
    """
    data = request.json

    text = data.get("text", "")
    scheduled_time = data.get("scheduled_time", "")

    if not text or not scheduled_time:
        return jsonify({
            "status": "error",
            "message": "Both text and scheduled_time are required"
        }), 400

    # FIX: Write to /Inbox (NOT /Briefings)
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    inbox_file = VAULT / "Inbox" / f"LINKEDIN_SCHEDULED_{timestamp}.md"

    content = f"""---
type: linkedin_post_scheduled
source: mcp
text: {text[:100]}...
scheduled_time: {scheduled_time}
status: new
created: {timestamp}
---

# Scheduled LinkedIn Post Request

**Scheduled Time:** {scheduled_time}
**Created:** {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}

## Post Content

{text}

---

## Note

This scheduled post will be processed through normal workflow.
*Generated by LinkedIn MCP Server v0.1*
"""

    inbox_file.write_text(content, encoding="utf-8")

    return jsonify({
        "status": "success",
        "message": f"LinkedIn post scheduled for {scheduled_time}",
        "inbox_file": inbox_file.name
    })


# ==============================
# GET STATUS
# ==============================
@app.route("/status", methods=["GET"])
def status():
    """Get LinkedIn MCP server status"""
    # FIX: Check Inbox (correct architecture)
    pending_posts = list((VAULT / "Inbox").glob("LINKEDIN_POST_*.md"))
    scheduled_posts = list((VAULT / "Inbox").glob("LINKEDIN_SCHEDULED_*.md"))

    return jsonify({
        "status": "operational",
        "pending_in_inbox": len(pending_posts),
        "scheduled_in_inbox": len(scheduled_posts),
        "configured": bool(os.getenv("LINKEDIN_ACCESS_TOKEN"))
    })


# ==============================
# LOGGING
# ==============================
def log_linkedin_post(content: str, post_id: str, status: str):
    """Log LinkedIn post to Logs folder"""
    today = datetime.now().strftime("%Y-%m-%d")
    log_file = VAULT / "Logs" / f"{today}.md"
    
    timestamp = datetime.now().isoformat()
    log_entry = f"""
## [{timestamp}] LinkedIn Post
- **Status:** {status}
- **Post ID:** {post_id}
- **Content:** {content[:100]}...

"""
    
    if log_file.exists():
        log_content = log_file.read_text(encoding="utf-8")
    else:
        log_content = f"# Activity Log - {today}\n\n"
    
    log_content += log_entry
    log_file.write_text(log_content, encoding="utf-8")


# ==============================
# RUN SERVER
# ==============================
if __name__ == "__main__":
    # Ensure folders exist
    (VAULT / "Inbox").mkdir(exist_ok=True)
    (VAULT / "Logs").mkdir(exist_ok=True)

    print("="*60)
    print("  LinkedIn MCP Server - Silver Level")
    print("="*60)
    print("\nEndpoints:")
    print("  POST /create-post - Create LinkedIn post draft (writes to /Inbox)")
    print("  POST /execute-post - Execute approved post")
    print("  POST /schedule-post - Schedule post for later (writes to /Inbox)")
    print("  GET  /status - Get server status")
    print("\nCorrect Flow:")
    print("  MCP → /Inbox → Orchestrator → /Needs_Action → AI → Plans → Approval → Done")
    print("\nServer running on http://localhost:5001")
    print("="*60)

    app.run(port=5001, debug=True)
