"""
Orchestrator - Gold Tier Implementation
Master process that manages the AI Employee lifecycle
Coordinates: Watchers → Agent (Qwen) → Approval Handler → Actions

Gold Features:
- CEO Briefing generation (weekly)
- Failed task processing with retry
- Ralph Wiggum Loop integration
- Comprehensive audit logging

Lifecycle: Needs_Action → Plans → Pending_Approval → Approved → Done
"""
import time
from pathlib import Path
from datetime import datetime
from agent import process_all_tasks, ensure_folders as agent_ensure_folders
from approval_handler import run as handle_approval, check_rejected
from retry_handler import retry_failed_tasks, get_failed_tasks
from qwen_agent import load_context

VAULT = Path("AI_Employee_Vault")

# Folder paths
NEEDS_ACTION = VAULT / "Needs_Action"
PLANS = VAULT / "Plans"
PENDING_APPROVAL = VAULT / "Pending_Approval"
APPROVED = VAULT / "Approved"
DONE = VAULT / "Done"
LOGS = VAULT / "Logs"
BRIEFINGS = VAULT / "Briefings"
INBOX = VAULT / "Inbox"
FAILED = VAULT / "Failed"


def safe_read(file_path: Path) -> str:
    """
    Safely read file content with encoding fallback.
    Try UTF-8 first, fallback to latin-1 if decoding fails.
    """
    try:
        return file_path.read_text(encoding="utf-8")
    except UnicodeDecodeError:
        return file_path.read_text(encoding="latin-1")


def safe_write(file_path: Path, content: str):
    """
    Safely write file content with UTF-8 encoding.
    """
    file_path.write_text(content, encoding="utf-8")


def ensure_all_folders():
    """Ensure all required vault folders exist"""
    folders = [
        NEEDS_ACTION,
        PLANS,
        PENDING_APPROVAL,
        APPROVED,
        DONE,
        LOGS,
        BRIEFINGS,
        VAULT / "Inbox",
        FAILED,
        VAULT / "Memory"
    ]
    for folder in folders:
        folder.mkdir(exist_ok=True)
    
    # Ensure Company Handbook and Business Goals exist
    handbook = VAULT / "Company_Handbook.md"
    if not handbook.exists():
        handbook.write_text("""# Company Handbook

## Rules of Engagement

- Always be polite
- Do not send payments without approval
- Flag payments > $100
- Review all communications before sending
- Log all actions

## Approval Thresholds

| Action | Auto-Approve | Require Approval |
|--------|-------------|------------------|
| Email replies | Known contacts | New contacts, bulk |
| Payments | < $50 recurring | All new payees, > $100 |
| File operations | Create, read | Delete, move outside vault |

---
*Last updated: """ + datetime.now().strftime("%Y-%m-%d") + """*
""", encoding="utf-8")
        print("[Orchestrator] Created Company_Handbook.md")

    business_goals = VAULT / "Business_Goals.md"
    if not business_goals.exists():
        business_goals.write_text("""# Business Goals

## Monthly Targets
- Revenue Target: $5000
- Client Response Time: < 24 hours
- Invoice Payment Rate: > 90%

## Active Projects
1. Project Alpha - Due end of month
2. Client Onboarding Automation

---
*Last updated: """ + datetime.now().strftime("%Y-%m-%d") + """*
""", encoding="utf-8")
        print("[Orchestrator] Created Business_Goals.md")

    # Ensure Dashboard.md exists
    dashboard = VAULT / "Dashboard.md"
    if not dashboard.exists():
        update_dashboard("System initialized", "AI Employee Bronze started")


def update_dashboard(action: str, details: str):
    """Update the Dashboard.md with current state"""
    dashboard = VAULT / "Dashboard.md"
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    
    # Count items in each folder
    pending_count = len(list(NEEDS_ACTION.glob("*.md")))
    approval_count = len(list(PENDING_APPROVAL.glob("*.md")))
    done_count = len(list(DONE.glob("*.md")))
    
    content = f"""# Dashboard

*Last updated: {timestamp}*

## Summary
- **Pending Tasks:** {pending_count}
- **Awaiting Approval:** {approval_count}
- **Completed Today:** {done_count}

## Pending Tasks
"""
    
    # List pending tasks (max 10)
    pending_tasks = list(NEEDS_ACTION.glob("*.md"))[:10]
    if pending_tasks:
        for task in pending_tasks:
            content += f"- [ ] {task.name}\n"
    else:
        content += "- None\n"
    
    content += "\n## Awaiting Approval\n"
    approval_tasks = list(PENDING_APPROVAL.glob("*.md"))[:10]
    if approval_tasks:
        for task in approval_tasks:
            content += f"- [WAITING] {task.name}\n"
    else:
        content += "- None\n"

    content += f"""
## Recent Activity
- [{timestamp}] {action}: {details}

---
*Generated by AI Employee v0.1 - Bronze Level*
"""

    safe_write(dashboard, content)


def log_event(event_type: str, message: str):
    """Log an event to the Logs folder"""
    today = datetime.now().strftime("%Y-%m-%d")
    log_file = LOGS / f"{today}.md"

    timestamp = datetime.now().isoformat()
    log_entry = f"""## [{timestamp}] {event_type}
{message}

"""

    if log_file.exists():
        content = safe_read(log_file)
    else:
        content = f"# Activity Log - {today}\n\n"

    content += log_entry
    safe_write(log_file, content)


def check_health():
    """
    Check system health and log status
    
    Returns:
        dict with health status
    """
    health = {
        'vault_exists': VAULT.exists(),
        'needs_action_count': len(list(NEEDS_ACTION.glob("*.md"))),
        'pending_approval_count': len(list(PENDING_APPROVAL.glob("*.md"))),
        'approved_count': len(list(APPROVED.glob("*.md"))),
        'logs_folder_exists': LOGS.exists(),
        'handbook_exists': (VAULT / "Company_Handbook.md").exists(),
        'business_goals_exists': (VAULT / "Business_Goals.md").exists(),
    }
    health['status'] = 'healthy' if all([
        health['vault_exists'],
        health['logs_folder_exists'],
        health['handbook_exists']
    ]) else 'degraded'
    
    return health


def process_inbox():
    """
    Move files from /Inbox to /Needs_Action for processing.
    
    Per document architecture:
    - Watchers write to /Inbox
    - Orchestrator moves /Inbox → /Needs_Action
    - AI processes /Needs_Action
    """
    inbox_items = list(INBOX.glob("*.md"))
    moved = 0
    
    for item in inbox_items:
        try:
            dest = NEEDS_ACTION / item.name
            item.rename(dest)
            print(f"[Orchestrator] Moved {item.name} from Inbox to Needs_Action")
            moved += 1
        except Exception as e:
            print(f"[Orchestrator] Error moving {item.name}: {e}")
    
    return moved


def run_cycle():
    """
    Run one complete cycle of the AI Employee (Gold Tier)

    1. Move files from Inbox to Needs_Action
    2. Process tasks from Needs_Action (create plans, request approvals)
    3. Handle approved files (execute actions)
    4. Check rejected files
    5. Process failed tasks (retry)
    6. Update dashboard

    Returns:
        dict with cycle statistics
    """
    stats = {
        'inbox_processed': 0,
        'tasks_processed': 0,
        'approvals_handled': 0,
        'rejected_checked': 0,
        'failed_retried': 0
    }

    print("\n" + "="*50)
    print(f"[Orchestrator] Starting cycle at {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    print("="*50)

    # Step 1: Move files from Inbox to Needs_Action
    print("\n[Orchestrator] Step 1: Processing Inbox...")
    stats['inbox_processed'] = process_inbox()

    # Step 2: Process tasks from Needs_Action
    print("\n[Orchestrator] Step 2: Processing tasks...")
    stats['tasks_processed'] = process_all_tasks()

    # Step 3: Handle approved files
    print("\n[Orchestrator] Step 3: Handling approvals...")
    stats['approvals_handled'] = handle_approval()

    # Step 4: Check rejected files
    print("\n[Orchestrator] Step 4: Checking rejected files...")
    check_rejected()

    # Step 5: Retry failed tasks
    print("\n[Orchestrator] Step 5: Retrying failed tasks...")
    stats['failed_retried'] = retry_failed_tasks()

    # Step 6: Update dashboard
    print("\n[Orchestrator] Step 6: Updating dashboard...")
    update_dashboard(
        "Cycle completed",
        f"Inbox: {stats['inbox_processed']}, Tasks: {stats['tasks_processed']}, Approvals: {stats['approvals_handled']}, Retried: {stats['failed_retried']}"
    )

    # Step 7: Log cycle
    log_event(
        "cycle_complete",
        f"Tasks: {stats['tasks_processed']}, Approvals: {stats['approvals_handled']}, Retried: {stats['failed_retried']}"
    )

    print(f"\n[Orchestrator] Cycle complete. Stats: {stats}")
    print("="*50 + "\n")

    return stats


def main():
    """
    Main orchestrator loop
    
    Runs continuously, checking for new tasks and processing approvals.
    Cycle interval: 30 seconds (configurable)
    """
    print("="*60)
    print("  AI Employee - Bronze Level")
    print("  Orchestrator Starting...")
    print("="*60)
    
    # Initialize
    ensure_all_folders()
    
    # Log startup
    log_event("startup", "AI Employee Bronze orchestrator started")
    
    # Check initial health
    health = check_health()
    print(f"\n[Orchestrator] System Health: {health['status']}")
    print(f"  - Vault exists: {health['vault_exists']}")
    print(f"  - Handbook exists: {health['handbook_exists']}")
    print(f"  - Business Goals exists: {health['business_goals_exists']}")
    print(f"  - Pending tasks: {health['needs_action_count']}")
    print(f"  - Pending approvals: {health['pending_approval_count']}")
    
    # Load context
    print("\n[Orchestrator] Loading context (Company Handbook, Business Goals)...")
    handbook, goals = load_context()
    if handbook:
        print("  - Company Handbook loaded ✓")
    if goals:
        print("  - Business Goals loaded ✓")
    
    print("\n[Orchestrator] Starting main loop (30 second intervals)...")
    print("Press Ctrl+C to stop\n")
    
    cycle_count = 0
    
    try:
        while True:
            cycle_count += 1
            print(f"\n[Orchestrator] === Cycle {cycle_count} ===")
            
            # Run one cycle
            run_cycle()
            
            # Wait before next cycle
            time.sleep(30)
            
    except KeyboardInterrupt:
        print("\n\n[Orchestrator] Shutting down...")
        log_event("shutdown", f"Orchestrator stopped after {cycle_count} cycles")
        update_dashboard("System shutdown", f"Stopped after {cycle_count} cycles")
        print("[Orchestrator] Goodbye!")


if __name__ == "__main__":
    main()
