"""
Retry Handler - Gold Tier
Implements error recovery with exponential backoff

Per hackathon document:
"Error recovery and graceful degradation"
"Retry Logic with exponential backoff"

Features:
- Retry failed operations with exponential backoff
- Max attempts configuration
- Failed task tracking in /Failed folder
- Graceful degradation when components fail
"""
import time
import functools
from pathlib import Path
from datetime import datetime
import logging

VAULT = Path("AI_Employee_Vault")
FAILED = VAULT / "Failed"

# Configure logging
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(name)s - %(levelname)s - %(message)s'
)
logger = logging.getLogger(__name__)


def ensure_failed_folder():
    """Ensure /Failed folder exists"""
    FAILED.mkdir(exist_ok=True)
    return FAILED


def move_to_failed(file_path: Path, error: str, operation: str = "unknown"):
    """
    Move a file to /Failed folder with error metadata
    """
    ensure_failed_folder()

    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    failed_file = FAILED / f"FAILED_{file_path.stem}_{timestamp}.md"

    content = f"""---
type: failed_task
original_file: {file_path.name}
error: {error}
operation: {operation}
timestamp: {datetime.now().isoformat()}
status: failed
---

# Failed Task

**Original File:** {file_path.name}
**Operation:** {operation}
**Error:** {error}
**Failed At:** {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}

## Recovery Instructions

This task failed during processing.

**Options:**
1. **Manual Fix:** Review the error above, fix the issue, then move this file to /Needs_Action for reprocessing
2. **Archive:** Move to /Rejected if the task is no longer needed
3. **Retry:** Move back to /Needs_Action to retry processing

---
*Generated by Retry Handler v0.1*
"""

    try:
        # Copy original content if possible
        if file_path.exists():
            original = file_path.read_text(encoding="utf-8", errors="replace")
            content += f"\n## Original Content\n\n{original}\n"
        failed_file.write_text(content, encoding="utf-8")
        logger.info(f"Moved to Failed: {failed_file.name}")
    except Exception as e:
        logger.error(f"Failed to create failed file: {e}")


def with_retry(max_attempts=3, base_delay=1, max_delay=60, operation="unknown"):
    """
    Decorator for retry with exponential backoff

    Args:
        max_attempts: Maximum number of retry attempts
        base_delay: Initial delay between retries (seconds)
        max_delay: Maximum delay between retries (seconds)
        operation: Name of operation for logging
    """
    def decorator(func):
        @functools.wraps(func)
        def wrapper(*args, **kwargs):
            last_error = None

            for attempt in range(max_attempts):
                try:
                    return func(*args, **kwargs)
                except Exception as e:
                    last_error = e
                    delay = min(base_delay * (2 ** attempt), max_delay)

                    logger.warning(
                        f"Attempt {attempt + 1}/{max_attempts} failed for {operation}: {e}. "
                        f"Retrying in {delay}s..."
                    )

                    if attempt < max_attempts - 1:
                        time.sleep(delay)

            # All attempts failed
            logger.error(f"All {max_attempts} attempts failed for {operation}: {last_error}")

            # Move to failed folder if file path provided
            if args and hasattr(args[0], 'name'):
                move_to_failed(args[0], str(last_error), operation)

            return None

        return wrapper
    return decorator


def retry_failed_tasks() -> int:
    """
    Retry all tasks in /Failed folder by moving them back to /Needs_Action
    Returns number of tasks retried
    """
    ensure_failed_folder()

    failed_files = list(FAILED.glob("FAILED_*.md"))
    retried = 0

    for failed_file in failed_files:
        try:
            content = failed_file.read_text(encoding="utf-8", errors="replace")

            # Extract original file name from frontmatter
            if "original_file:" in content:
                original_name = content.split("original_file:")[1].split("\n")[0].strip()

                # Create new task file in Needs_Action
                needs_action = VAULT / "Needs_Action"
                needs_action.mkdir(exist_ok=True)

                new_file = needs_action / f"RETRY_{original_name}"
                new_file.write_text(content, encoding="utf-8")

                # Remove from Failed
                failed_file.unlink()

                logger.info(f"Retried: {original_name}")
                retried += 1

        except Exception as e:
            logger.error(f"Failed to retry {failed_file.name}: {e}")

    return retried


def get_failed_tasks() -> list:
    """Get list of failed tasks"""
    ensure_failed_folder()

    failed_files = list(FAILED.glob("FAILED_*.md"))
    tasks = []

    for f in failed_files:
        try:
            content = f.read_text(encoding="utf-8", errors="replace")
            tasks.append({
                "file": f.name,
                "content": content[:200]
            })
        except Exception:
            continue

    return tasks


if __name__ == "__main__":
    # Show failed
    failed = get_failed_tasks()

    if failed:
        print(f"\nFailed Tasks ({len(failed)}):")
        for task in failed:
            print(f"  - {task['file']}")
    else:
        print("\nNo failed tasks.")

    # Optionally retry
    if failed:
        response = input("\nRetry failed tasks? (y/n): ")
        if response.lower() == 'y':
            retried = retry_failed_tasks()
            print(f"\nRetried {retried} tasks.")
